// <auto-generated />
namespace SAPTechnicalTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SAP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SAP));
        
        string IMigrationMetadata.Id
        {
            get { return "201609010428242_SAP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
